name: git-mirror-action
description: mirrors a git repository to another
author: Mathis Van Eetvelde
inputs:
  originalURL:
    description: url of the repository you want to mirror
    required: true
  originalBranch:
    description: branch in the original repository you want to mirror. Defaults to `master`
    required: false
  mirrorURL:
    description: url of the repository you want the mirror to go in
    required: true
  mirrorBranch:
    description: branch that will be created or pushed into. Defaults to `mirror`
    required: false
  patEncoded:
    description: Base64 encoded Personal Access Token
    required: true
  useForce:
    description: whether to use the `--force` argument when pushing to the mirror repository. Defaults to false
    required: false

runs:
  using: docker
  image: Dockerfile